# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: validate_url 1.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "validates_airline_addendum"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Andrei Novikau"]
  s.date = "2016-03-28"
  s.description = "Library for validating airline data in Rails."
  s.email = ["greentlalok@gmail.com"]
  s.extra_rdoc_files = [
    "LICENSE.md",
    "README.md"
  ]
  s.files = [
    "init.rb",
    "install.rb",
    "lib/validates_airline_addendum.rb"
  ]
  s.homepage = "https://github.com/seongreen/validates_airline_addendum/tree/master"
  s.summary = "Library for validating airline data."

  s.add_dependency('activemodel', [">= 3.0.0"])
  s.add_dependency('rspec', [">= 0"])
end
